###
GET http://localhost:1234/productos


 
###
GET http://localhost:1234/usuarios

###
POST http://localhost:1234/usuarios
Content-Type: application/json

{
    "usuario" : "Sofy",
    "contraseña" : "12345"
}

###