###
GET http://localhost:8000/productos
###
POST http://localhost:8000/productos/create
Content-Type: application/json

{
    "nombre" : "Sfijas",
    "descripcion" : "Lo mejor de Salta la Linda",
    "cantidad" : 30,
    "precio" : 500.00
}

###  
GET http://localhost:8000/usuarios

###
POST http://localhost:8000/usuarios/update
Content-Type: application/json

{
    "userName" : "admin",
    "password" : "123"
}


###  
POST http://localhost:8000/login
Content-Type: application/json

{
    "userName" : "admin",
    "userPassword" : "123"
}

###
GET http://localhost:8000/sales

###
POST http://localhost:8000/sales/sale
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA1NzA5ODQzfQ.bwPxEBpGdYlHrydj4RQRIGueq2x3JzIlkjW2g8uXmdQ

{
    "idProducto" : 1,
    "idUsuario" : null,
    "cantidad" : 8,
    "total" : 846.00,
    "fecha" : "2024/1/18"
}

### 
POST http://localhost:8000/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA1Nzg2Nzc0fQ.lH0TWmNLeUsvy1jjmrOtTGHA87Mq9yVOgK8-xNiSlPM


{
    "usuario" : "tanito",
    "contraseña" : "tanito123",
    "rol" : "vendedor"
}