###
GET http://localhost:8000/productos
###
POST http://localhost:8000/productos/create
Content-Type: application/json

{
    "nombre" : "Sfijas",
    "descripcion" : "Lo mejor de Salta la Linda",
    "cantidad" : 30,
    "precio" : 500.00
}


 
### 
GET http://localhost:8000/usuarios

###  
POST http://localhost:8000/login
Content-Type: application/json

{
    "userName" : "tanito",
    "userPassword" : "tanito"
}

###
GET http://localhost:8000/sales

###
POST http://localhost:8000/sales/sale
Content-Type: application/json

{
    "idProducto" : 4,
    "idUsuario" : 7,
    "cantidad" : 5,
    "total" : 525.00,
    "fecha" : "2024/1/4"
}